version: '2'

networks:
    bibbox-default-network:
      external: true

services:

  §§INSTANCE-galaksio:
    image: bibbox/galaksio
    container_name:  §§INSTANCE-galaksio
    restart: unless-stopped
    networks:
      - bibbox-default-network
    ports:
      - §§PORT:80
    depends_on:
      - §§INSTANCE-galaksio-data
    volumes_from:
      - §§INSTANCE-galaksio-data

  §§INSTANCE-galaksio-data:
    image: busybox
    container_name: §§INSTANCE-galaksio-data
    volumes:
      - ./var/www/galaksio:/usr/local/apache2/htdocs/server/conf/
